const randomphrases = [
  "When you realize it's Monday tomorrow",
  "When you're the only sober one at the party",
  "When your mom says she's not mad",
  "When you see a spider in your room",
  "When you're trying to be cool in front of your crush",
  "When you're the only one who didn't get the joke",
  "When you're trying to act like you're listening",
  "When your meal is spicy as heck but you're acting like it's not",
  "When you realize that you never hit SEND on a pretty important text",
  "When someone says, No offense, and you know they're gonna offend you",
  "When someone says they're a morning person",
  "When you're trying to be a good friend but they cancel plans",
  "When you're trying to make a good impression but you're too awkward",
  "When you're trying to act natural in front of a crush",
  "When you're the only one not invited to the party",
  "When you're trying to be healthy but all you want is junk food",
  "When someone tells you that you chew too loud",
  "When your new neighbor is way too friendly",
  "When your alarm goes off for work but it's Saturday",
  "When a supermarket employee catches you sampling the grapes",
  "When you're trying to be cool but you're still a nerd",
  "When a friend who works at a restaurant tells you what really goes on the kitchen",
  "When you've got an itch in your butt crack that just won't quit",
  "When you're trying to be a good listener but your mind is elsewhere",
  "When your mom asks if you want to do something fun and it turns out her idea of fun is a puzzle",
  "When the weather forecast calls for sun and it rains all day",
  "When you're trying to be a good roommate but they're too messy",
  "When you text something funny to a friend and you're just waiting for their reply",
  "When you're trying to be a good human but society is flawed",
  "When you're trying to be productive but Netflix is calling your name",
  "When you're trying to be healthy but pizza is your true love",
  "When your Amazon order comes earlier than the expected delivery date",
  "When you accidentally FaceTime your crush while on the toilet",
  "When the website says a store is open but you show up and they're closed",
  "When you just know you're about to break your 'number of days without crying' streak",
  "When you're trying to be a good friend but they're constantly cancelling plans",
  "When you're trying to be a good partner but they're not meeting your expectations",
  "When a guest just doesn't get the hint tha it's time for them to leave",
  "When someone says you look tired the day after you finally got a lot of sleep",
  "When the waiter comes back to ask how the food is 10 seconds after dropping it off at the table",
  "When you're trying to be a good driver but the traffic is making you late",
  "When you're trying to be a good cook but the recipe is too complicated",
  "When you're trying to be a good host but the guests are too demanding",
  "When you're trying to be a good traveler but the flight is delayed",
  "When you're trying to be a good sport but you're losing the game",
  "When it is Christmas and your first three gifts are underwear",
  "When someone spoils a movie or TV show on purpose",
  "When you're trying to be a good listener but your mind is on your phone",
  "When you're trying to be a good person but the world is full of jerks",
  "When someone whishes you a happy birthday but it's not your birthday",
  "When your friend takes a bite of your lunch without asking",
  "When you answer the teacher's question with a ton of confidence and she tells you that you're wrong",
  "When you're trying to be a good parent but your kids are driving you nuts",
  "When your birthday falls on a holiday and everyone forgets that it's your birthday",
  "When you have to take your shoes off at someone's house and your sock has a hole",
  "When your boss starts following you on TikTok",
  "When one of your own farts wakes you up in the morning",
  "When you think no one can hear so you rip a loud one",
  "When you are trying to tell a story but the other person won't stop interrupting",
  "That look you give when someone tells you they love to go fishing",
  "When you think you're going to be late but you're actually on time",
  "When you realize you're talking with a close talker",
  "When you're trying to be a good sport but the rules are too confusing",
  "When Grandma wants to tell you all about the trouble she is been having going to the bathroom",
  'When the waiter tells you to enjoy your food and you respond "You too!',
  "When you're trying to be a good listener but your mind is on the food",
  "When you're trying to be a good person but the world is too judgmental",
  "When you're trying to be a good employee but the boss is too demanding",
  "When you order delivery and the food just never shows up",
  "When you're talking with someone and they have food in their teeth",
  "When you're trying to be a good friend but they're too flaky",
  "When you're trying to be a good partner but they're too possessive",
  "When you're trying to be a good citizen but the government is too inefficient",
  "When you're trying to be a good human but the world is too chaotic",
  "When you spit out the window of a moving car and the loogie hits you right in the face",
  "When you sit on something dirty and it leaves a brown stain on your butt",
  "When you're trying to be a good cook but the recipe is too daunting",
  "When you're trying to be a good host but the guests are too nosy",
  "When you're trying to be a good traveler but the trip is too stressful",
  "When you're trying to be a good sport but the competition is too fierce",
  "The face you make when someone compliments your haircut",
  "When you're trying to be a good shopper but the mall is too crowded",
  "When you're trying to be a good listener but your mind is on the weather",
  "When you're trying to be a good person but the world is too cruel",
  "When you fake being sick to get out of something and end up actually getting sick",
  "When you're trying to be a good student but the class is too difficult",
  "When you're trying to be a good parent but your kids are too disobedient",
  "When you're trying to be a good friend but they're too unreliable",
  "When you find a couple bucks in your pants",
  "When you're trying to be a good citizen but the government is too corrupt",
  "When you're trying to be a good human but the world is too selfish",
  "When the stranger next to you at the theater takes a phone call during the movie",
  "When you're trying to be a good driver but the roads are too dangerous",
  "When you show someone a hilarious video and they don't laugh",
  "When you're trying to be a good host but the guests are too demanding",
  "When you're trying to be a good traveler but the destination is too touristy",
  "When you're trying to be a good sport but the equipment is too old",
  "When you're staying at a hotel and find a hair that's not yours on the pillow",
  "When you leave the house and you're not dressed for the weather",
];

export default randomphrases;
